/* sql_utils.js
 * Contains Sequelize function to connect to database
 * Loads all model files associated with database, this should have been generated using gen_models.js
 */

var Sequelize = require('sequelize') // MySQL ORM 
    , path = require('path') // Core Node module for working with and handling paths
    , config = require(path.join(__dirname, 'config')) // Hides secret configuration info
    , sequelize = new Sequelize(config.seq.database, config.seq.username, config.seq.password, config.seq.options);

// Check database connection
sequelize
    .authenticate()
    .then(function(err) {
        console.log('Connection has been established successfully.');
    })
    .catch(function(err) {
        console.log('Unable to connect to the database:', err);
    });

// Load all model files generated by sequelize-auto
require("fs").readdirSync(path.join(__dirname, "models")).forEach(function(file) {
    sequelize.import(path.join(__dirname, "models", file));
    //console.log("Loaded " + path.join(__dirname, "models", file));
});

module.exports = sequelize;
